[package]
name = "bat3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
beep = "0.3.0"
rodio = "0.12.0"

async-std = "1.2"
futures = "0.3.1"
